package biblioteca.simple.app;

public class Main {
    public static void main(String[] args) {

    }
}

// TODO TODO DENTRO DEL MAIN
// TODO DEFINIR UN NUEVO OBJETO DE TIPO CATALOGO PARA USARLO EN MAIN
// TODO DECLARAR LISTA DE USUARIOS
// TODO HACER CARGA A MACHETE DE LIBROS Y PELICULAS
// TODO CARGA DE USUARIOS
// TODO MENU PRINCIPAL (1. LISTA 2. BUSCAR POR TITULO 3. BUSCAR POR AÑO 4. PRESTTAR 5. DEVOLVER 6. SALIR )
// TODO PRESTAR ¿QUE PRODUCTO?, MOSTRAR PRODUCTOS DISPONIBLES, ¿A QUE USUARIO?
// TODO DEVOLVER, QUE PRODUCTO?.
